# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)

<% %w(development test production).each do |env| %>

<%= env %>:
  adapter: sqlite3
  database: <%= "db/#{env}.sqlite3" %>
  timeout: 5000

<%= "shard_0_#{env}" %>:
  adapter: sqlite3
  database: <%= "db/s0_#{env}.sqlite3" %>
  timeout: 5000

<%= "shard_1_#{env}" %>:
  adapter: sqlite3
  database: <%= "db/s1_#{env}.sqlite3" %>
  timeout: 5000

<% end %>